title: Heidi Dong
description: a small website representing some of heidi's interests & past projects. 
social:
  name: Heidi Dong
  links:
    - https://twitter.com/enhdless
    - https://github.com/heidid
    - https://www.linkedin.com/in/heididong/